### ISSUE TITLE
"Could not start MOD Host. Process crashed." error on JACK/PipeWire setting

### ISSUE THREAD

**Issue by Inqb8tr-jp** [moddevices/mod-desktop#41]
I downloaded ver 0.0.7 on my Manjaro Linux with MOTU M4 audio interface.
Works fine when I select "M4, USB Audio (hw:4,0)" but the audio interface disappears on the qpwgraph.
When I select "JACK/PipeWire," the error "Could not start MOD Host. Process crashed." window pops up.
![screenshot_2024-02-04T16:45:10](https://github.com/moddevices/mod-desktop/assets/79005925/5f4d13ee-8fad-4748-beb1-50ec90623625)

The following output appears on the console.
```
--------------------------------------------------------
/usr/lib/libjack.so.0 loaded successfully!
--------------------------------------------------------
----------- loadSettings 654
----------- updateDeviceDetails 1028 | 7 8
----------- setStopped 782
kf.windowsystem: Could not find any platform plugin
----------- saveSettings 624
----------- start 872
----------- setStarting 758
----------- hostStartSuccess 1088
----------- hostStartError 1051
----------- setStopped 782
----------- getProcessErrorAsString 797
----------- showErrorMessage 811
----------- hostFinished 1100
----------- stopUIIfNeeded 830
----------- setStopped 782
```

**Comment by falkTX** [comment]
if you run the included jackd (same dir as the mod-desktop binary) with the CLI arguments as described in the logs, does that work?

**Comment by Inqb8tr-jp** [comment]
Thank you for your reply.
I got the following output.
```
$ ./jackd -R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d portaudio -r 48000 -p 256 -d JACK::system
jackdmp 1.9.22
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2023 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
Could not open driver directory /github/home/PawPawBuilds/targets/linux-x86_64/lib/jack: No such file or directory
Could not find any drivers in driver directory!
Failed to create server object
```

**Comment by falkTX** [comment]
right, it needs a little env var first, just this:
```
export JACK_DRIVER_DIR="$(pwd)/jack"
./jackd ...
```

**Comment by Inqb8tr-jp** [comment]
```
$ ./jackd -R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d portaudio -r 48000 -p 256
 -d JACK::system
jackdmp 1.9.22
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2023 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Jack: JackPosixThread::StartImp : create non RT thread
Jack: JackPosixThread::ThreadHandler : start
Jack: Initializing PortAudio...
libjack.so.0 loaded successfully!
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Jack: JackPortAudioDriver::Open nframes = 256 in = 0 out = 0 capture name = JACK::system playback name = JACK::system samplerate = 48000
Can't open JACK::system, PortAudio will use default input device.
Can't open default PortAudio device
Jack: Terminate PortAudio...
Jack: ~JackDriver
Cannot initialize driver
Jack: no message buffer overruns
Jack: JackPosixThread::Stop
Jack: JackPosixThread::ThreadHandler : exit
JackServer::Open failed with -1
Jack: Succeeded in unlocking 107341340 byte memory area
Jack: JackShmMem::delete size = 0 index = 0
Jack: ~JackDriver
Jack: Succeeded in unlocking 1196 byte memory area
Jack: JackShmMem::delete size = 0 index = 1
Jack: Cleaning up shared memory
Jack: Cleaning up files
Jack: Unregistering server `mod-desktop'
Failed to open server
```

**Comment by falkTX** [comment]
from the logs I see it never tries to connect with pipewire, and tries to use regular system jack2

you are using pipewire, correct? do you have the pipewire-jack stuff enabled?
also, what is your pipewire version?

maybe try running as `pw-jack ./jackd ...`

**Comment by Inqb8tr-jp** [comment]
```
$ pipewire --version
pipewire
Compiled with libpipewire 1.0.0
Linked with libpipewire 1.0.0
```

I got the following output.
```
 pw-jack ./jackd -R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d portaudio -r 4800
0 -p 256 -d JACK::system
jackdmp 1.9.22
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2023 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Jack: JackPosixThread::StartImp : create non RT thread
Jack: JackPosixThread::ThreadHandler : start
Jack: Initializing PortAudio...
libjack.so.0 loaded successfully!
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Jack: JackPortAudioDriver::Open nframes = 256 in = 0 out = 0 capture name = JACK::system playback name = JACK::system samplerate = 48000
Can't open JACK::system, PortAudio will use default input device.
Can't open default PortAudio device
Jack: Terminate PortAudio...
Jack: ~JackDriver
Cannot initialize driver
Jack: no message buffer overruns
Jack: JackPosixThread::Stop
Jack: JackPosixThread::ThreadHandler : exit
JackServer::Open failed with -1
Jack: Succeeded in unlocking 107341340 byte memory area
Jack: JackShmMem::delete size = 0 index = 0
Jack: ~JackDriver
Jack: Succeeded in unlocking 1196 byte memory area
Jack: JackShmMem::delete size = 0 index = 1
Jack: Cleaning up shared memory
Jack: Cleaning up files
Jack: Unregistering server `mod-desktop'
Failed to open server
```

**Comment by falkTX** [comment]
even with that it cannot find the pipewire-jack libs, something is off.. I only tried this on a debian system and it was working there.

see if you find where the pipewire jack lib is located, and set an env var to it, like this:
```
export JACKBRIDGE_FILENAME=/usr/lib/pipewire-0.3/jack/libjack.so.0
export JACK_DRIVER_DIR="$(pwd)/jack"
./jackd ...
```

**Comment by Inqb8tr-jp** [comment]
```
$ export JACKBRIDGE_FILENAME=/usr/lib/libjack.so.0
$ export JACK_DRIVER_DIR="$(pwd)/jack"
$  ./jackd -R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d portaudio -r 48000 -p 256 -d JACK::system 
jackdmp 1.9.22
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2023 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Jack: JackPosixThread::StartImp : create non RT thread
Jack: JackPosixThread::ThreadHandler : start
Jack: Initializing PortAudio...
/usr/lib/libjack.so.0 loaded successfully!
Jack: JackPortAudioDriver::Open nframes = 256 in = 0 out = 0 capture name = JACK::system playback name = JACK::system samplerate = 48000
Jack: JackDriver::Open capture_driver_name = JACK::system
Jack: JackDriver::Open playback_driver_name = JACK::system
Jack: Check protocol client = 9 server = 9
Jack: JackEngine::ClientInternalOpen: name = system
Jack: JackEngine::AllocateRefNum ref = 0
Jack: JackLinuxFutex::Allocate name = jack_sem.1000_mod-desktop_system val = 0
Jack: JackEngine::NotifyAddClient: name = system
Jack: JackGraphManager::SetBufferSize size = 256
Jack: JackConnectionManager::DirectConnect first: ref1 = 0 ref2 = 0
Jack: JackGraphManager::ConnectRefNum cur_index = 0 ref1 = 0 ref2 = 0
Jack: JackDriver::SetupDriverSync driver sem in normal mode
Jack: JackPortAudioDriver::Open fInputDevice = 0, fOutputDevice 0
Jack: JackPortAudioDriver::Open setup max in channels = 2
Jack: JackPortAudioDriver::Open setup max out channels = 2
Jack: JackPortAudioDriver::OpenStream buffer_size = 256
[1]    36474 segmentation fault (core dumped)  ./jackd -R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d  -r  
```

**Comment by Inqb8tr-jp** [comment]
I think pipewire-jack libs is /usr/lib/libjack.so.0 .
I've installed pipewire-jack and the package include following files.
```
$ pacman -Ql pipewire-jack
pipewire-jack /etc/
pipewire-jack /etc/pipewire/
pipewire-jack /etc/pipewire/jack.conf.d/
pipewire-jack /usr/
pipewire-jack /usr/bin/
pipewire-jack /usr/bin/pw-jack
pipewire-jack /usr/include/
pipewire-jack /usr/include/jack/
pipewire-jack /usr/include/jack/control.h
pipewire-jack /usr/include/jack/intclient.h
pipewire-jack /usr/include/jack/jack.h
pipewire-jack /usr/include/jack/jslist.h
pipewire-jack /usr/include/jack/metadata.h
pipewire-jack /usr/include/jack/midiport.h
pipewire-jack /usr/include/jack/net.h
pipewire-jack /usr/include/jack/ringbuffer.h
pipewire-jack /usr/include/jack/session.h
pipewire-jack /usr/include/jack/statistics.h
pipewire-jack /usr/include/jack/systemdeps.h
pipewire-jack /usr/include/jack/thread.h
pipewire-jack /usr/include/jack/transport.h
pipewire-jack /usr/include/jack/types.h
pipewire-jack /usr/include/jack/uuid.h
pipewire-jack /usr/include/jack/weakjack.h
pipewire-jack /usr/include/jack/weakmacros.h
pipewire-jack /usr/lib/
pipewire-jack /usr/lib/libjack.so
pipewire-jack /usr/lib/libjack.so.0
pipewire-jack /usr/lib/libjack.so.0.3.1000
pipewire-jack /usr/lib/libjacknet.so
pipewire-jack /usr/lib/libjacknet.so.0
pipewire-jack /usr/lib/libjacknet.so.0.3.1000
pipewire-jack /usr/lib/libjackserver.so
pipewire-jack /usr/lib/libjackserver.so.0
pipewire-jack /usr/lib/libjackserver.so.0.3.1000
pipewire-jack /usr/lib/pkgconfig/
pipewire-jack /usr/lib/pkgconfig/jack.pc
pipewire-jack /usr/share/
pipewire-jack /usr/share/licenses/
pipewire-jack /usr/share/licenses/pipewire-jack/
pipewire-jack /usr/share/licenses/pipewire-jack/COPYING
pipewire-jack /usr/share/man/
pipewire-jack /usr/share/man/man1/
pipewire-jack /usr/share/man/man1/pw-jack.1.gz
pipewire-jack /usr/share/pipewire/
pipewire-jack /usr/share/pipewire/jack.conf
pipewire-jack /usr/share/pipewire/media-session.d/
pipewire-jack /usr/share/pipewire/media-session.d/with-jack
```

**Comment by falkTX** [comment]
the one with the "segmentation fault" looks good, it crashes just like on the GUI side startup.
start it with gdb (as `gdb -- jackd ...`), then `r` to run and `bt` to get a trace of the crash.

**Comment by Inqb8tr-jp** [comment]
I'm sorry I don't know well about gdb.
```
gdb --  ./jackd -R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d portaudio -r 48000 -p 256 -d JACK::system 
Excess command line arguments ignored. (-S ...)
GNU gdb (GDB) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./jackd...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /home/aki/bin/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jackd
(No debugging symbols found in ./jackd)                                                                                                                       
/home/aki/bin/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/-R: No such file or directory.
(gdb) r
Starting program: /home/aki/bin/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jackd 
Downloading separate debug info for /lib64/ld-linux-x86-64.so.2
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc8000                                                                                     
Downloading separate debug info for /home/aki/bin/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/libjackserver.so.0                                            
Downloading separate debug info for /usr/lib/libc.so.6                                                                                                        
[Thread debugging using libthread_db enabled]                                                                                                                 
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Downloading separate debug info for /usr/lib/libpthread.so.0
Downloading separate debug info for /usr/lib/librt.so.1                                                                                                       
Downloading separate debug info for /usr/lib/libdl.so.2                                                                                                       
Downloading separate debug info for /usr/lib/libm.so.6                                                                                                        
Downloading separate debug info for /usr/lib/libsystemd.so.0                                                                                                  
Downloading separate debug info for /usr/lib/liblzma.so.5                                                                                                     
jackdmp 1.9.22                                                                                                                                                
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2023 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
Downloading separate debug info for /home/aki/bin/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/jack_dummy.so
Downloading separate debug info for /home/aki/bin/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/jack_portaudio.so                                        
Downloading separate debug info for /home/aki/bin/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/jack_alsa.so                                             
Downloading separate debug info for /home/aki/bin/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/alsa_midi.so                                             
Downloading separate debug info for /usr/lib/libjack.so.0                                                                                                     
Downloading separate debug info for /usr/lib/libpipewire-0.3.so.0                                                                                             
Downloading separate debug info for /usr/lib/spa-0.2/support/libspa-support.so                                                                                
Downloading separate debug info for /home/aki/bin/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/mod-midi-broadcaster.so                                  
Downloading separate debug info for /home/aki/bin/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/mod-host.so                                              
Downloading separate debug info for /home/aki/bin/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/mod-midi-merger.so                                       
                                                                                                                                                              
Usage: jackdmp [ --no-realtime OR -r ]
               [ --realtime OR -R [ --realtime-priority OR -P priority ] ]
      (the two previous arguments are mutually exclusive. The default is --realtime)
               [ --name OR -n server-name ]
               [ --timeout OR -t client-timeout-in-msecs ]
               [ --loopback OR -L loopback-port-number ]
               [ --port-max OR -p maximum-number-of-ports]
               [ --slave-backend OR -X slave-backend-name ]
               [ --internal-client OR -I internal-client-name ]
               [ --internal-session-file OR -C internal-session-file ]
               [ --verbose OR -v ]
               [ --clocksource OR -c [ h(pet) | s(ystem) ]
               [ --autoconnect OR -a <modechar>]
                 where <modechar> is one of:
                   ' ' - Don't restrict self connect requests (default)
                   'E' - Fail self connect requests to external ports only
                   'e' - Ignore self connect requests to external ports only
                   'A' - Fail all self connect requests
                   'a' - Ignore all self connect requests
               [ --replace-registry ]
               [ --silent OR -s ]
               [ --sync OR -S ]
               [ --temporary OR -T ]
               [ --version OR -V ]
         -d master-backend-name [ ... master-backend args ... ]
       jackdmp -d master-backend-name --help
             to display options for each master backend

[Inferior 1 (process 4043) exited with code 0377]
(gdb) bt
No stack.
(gdb) exit
```

**Comment by falkTX** [comment]
hmm I think it might need to be `gdb --args ./jackd ...` syntax, my bad

**Comment by victorolinasc** [comment]
Just to add to the thread... this is about the same in Fedora 39. 

```sh
Starting jackd using:
-R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d portaudio -r 48000 -p 128 -d JACK::system
jackdmp 1.9.22
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2023 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Jack: JackPosixThread::StartImp : create non RT thread
Jack: JackPosixThread::ThreadHandler : start
Jack: Initializing PortAudio...
/usr/lib64/pipewire-0.3/jack/libjack.so.0 loaded successfully!
Jack: JackPortAudioDriver::Open nframes = 128 in = 0 out = 0 capture name = JACK::system playback name = JACK::system samplerate = 48000
Jack: JackDriver::Open capture_driver_name = JACK::system
Jack: JackDriver::Open playback_driver_name = JACK::system
Jack: Check protocol client = 9 server = 9
Jack: JackEngine::ClientInternalOpen: name = system
Jack: JackEngine::AllocateRefNum ref = 0
Jack: JackLinuxFutex::Allocate name = jack_sem.1000_mod-desktop_system val = 0
Jack: JackEngine::NotifyAddClient: name = system
Jack: JackGraphManager::SetBufferSize size = 128
Jack: JackConnectionManager::DirectConnect first: ref1 = 0 ref2 = 0
Jack: JackGraphManager::ConnectRefNum cur_index = 0 ref1 = 0 ref2 = 0
Jack: JackDriver::SetupDriverSync driver sem in normal mode
Jack: JackPortAudioDriver::Open fInputDevice = 0, fOutputDevice 0
Jack: JackPortAudioDriver::Open setup max in channels = 2
Jack: JackPortAudioDriver::Open setup max out channels = 2
Jack: JackPortAudioDriver::OpenStream buffer_size = 128
```

No other messages on the gui (even with all logs switched on). 

Running both exports and the jack command on the GUI also goes nowhere here:

```sh
Music/mod-desktop-8d4e2463-linux-x86_64/mod-desktop 
❯ ./jackd -R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d portaudio -r 48000 -p 128 -d JACK::system
jackdmp 1.9.22
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2023 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
JACK server starting in realtime mode with priority 10
self-connect-mode is "Don't restrict self connect requests"
Jack: JackPosixThread::StartImp : create non RT thread
Jack: JackPosixThread::ThreadHandler : start
Jack: Initializing PortAudio...
Failed to load JACK DLL, reason:
/usr/lib/pipewire-0.3/jack/libjack.so.0: cannot open shared object file: No such file or directory
Jack: JackPortAudioDriver::Open nframes = 128 in = 0 out = 0 capture name = JACK::system playback name = JACK::system samplerate = 48000
Can't open JACK::system, PortAudio will use default input device.
Can't open default PortAudio device
Jack: Terminate PortAudio...
Jack: ~JackDriver
Cannot initialize driver
Jack: no message buffer overruns
Jack: JackPosixThread::Stop
Jack: JackPosixThread::ThreadHandler : exit
JackServer::Open failed with -1
Jack: Succeeded in unlocking 107341340 byte memory area
Jack: JackShmMem::delete size = 0 index = 0
Jack: ~JackDriver
Jack: Succeeded in unlocking 1196 byte memory area
Jack: JackShmMem::delete size = 0 index = 1
Jack: Cleaning up shared memory
Jack: Cleaning up files
Jack: Unregistering server `mod-desktop'
Failed to open server
```

Don't know much about GDB too sorry =/

My system is:
- Fedora 39 (non-RT kernel 6.6.14)
- libpipewire 1.0.2
- pipewire-jack-audio-connection-kit[-libs|-devel] installed
- Focusrite 2i4
- audio group and limits configured



```

```

**Comment by victorolinasc** [comment]
I've just checked and pipewire has a bug release 1.0.3 (not yet on Fedora) that says 

> Fix ALSA version check. This should allow the alsa plugin to work again.

Although it has nothing to do with jack per se and every other software audio is working here besides the mod-desktop.

I can try to run things here although I am more of a memory-safe language programmer and haven't melded much with C/C++ and GCC/GDB

Thanks for your wonderful work @falkTX I'll keep testing the betas or anything here!

**Comment by falkTX** [comment]
The Fedora part is not the same issue, this log line is very clear:

```
Failed to load JACK DLL, reason:
/usr/lib/pipewire-0.3/jack/libjack.so.0: cannot open shared object file: No such file or directory
```

something is missing?

**Comment by falkTX** [comment]
> The Fedora part is not the same issue, this log line is very clear:
> 
> ```
> Failed to load JACK DLL, reason:
> /usr/lib/pipewire-0.3/jack/libjack.so.0: cannot open shared object file: No such file or directory
> ```
> 
> something is missing?

oh yeah the export was meant for archlinux, not fedora.

on fedora the pw libs are found properly, you dont need to set the path to them.
anyhow, this is a completely different issue (just with similar results), please open a new ticket for it.

**Comment by magillos** [comment]
Here are my results when run in Arch. Maybe it will be somewhat helpful. Without running e. variables: 

```
gdb --args ./jackd -R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d portaudio -r 48000 -p 128 -d JACK::system
GNU gdb (GDB) 14.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./jackd...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jackd
(No debugging symbols found in ./jackd)                                                                                                                                                      
(gdb) r
Starting program: /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jackd -R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d portaudio -r 48000 -p 128 -d JACK::system
Downloading separate debug info for /lib64/ld-linux-x86-64.so.2
Downloading separate debug info for system-supplied DSO at 0x7ffff7fc8000                                                                                                                    
Downloading separate debug info for /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/libjackserver.so.0                                                                
Downloading separate debug info for /usr/lib/libc.so.6                                                                                                                                       
[Thread debugging using libthread_db enabled]                                                                                                                                                
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Downloading separate debug info for /usr/lib/libpthread.so.0
Downloading separate debug info for /usr/lib/librt.so.1                                                                                                                                      
Downloading separate debug info for /usr/lib/libdl.so.2                                                                                                                                      
Downloading separate debug info for /usr/lib/libm.so.6                                                                                                                                       
jackdmp 1.9.22                                                                                                                                                                               
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2023 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
Could not open driver directory /github/home/PawPawBuilds/targets/linux-x86_64/lib/jack: No such file or directory
Could not find any drivers in driver directory!
Failed to create server object
[Inferior 1 (process 100836) exited with code 0377]
(gdb) bt
No stack.
(gdb) quit 
```

and with e. variables: 

```
gdb --args ./jackd -R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d portaudio -r 48000 -p 128 -d JACK::system
GNU gdb (GDB) 14.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./jackd...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.archlinux.org>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
(No debugging symbols found in ./jackd)                                                                                                                                                      
(gdb) r
Starting program: /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jackd -R -S -n mod-desktop -C ./jack/jack-session-alsamidi.conf -v -d portaudio -r 48000 -p 128 -d JACK::system
[Thread debugging using libthread_db enabled]                                                                                                                                                
Using host libthread_db library "/usr/lib/libthread_db.so.1".
jackdmp 1.9.22                                                                                                                                                                               
Copyright 2001-2005 Paul Davis and others.
Copyright 2004-2016 Grame.
Copyright 2016-2023 Filipe Coelho.
jackdmp comes with ABSOLUTELY NO WARRANTY
This is free software, and you are welcome to redistribute it
under certain conditions; see the file COPYING for details
Downloading separate debug info for /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/jack_alsa.so
Downloading separate debug info for /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/jack_dummy.so                                                                
Downloading separate debug info for /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/jack_portaudio.so                                                            
Downloading separate debug info for /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/mod-midi-merger.so                                                           
Downloading separate debug info for /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/mod-midi-broadcaster.so                                                      
Downloading separate debug info for /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/alsa_midi.so                                                                 
Downloading separate debug info for /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/mod-host.so                                                                  
JACK server starting in realtime mode with priority 10                                                                                                                                       
self-connect-mode is "Don't restrict self connect requests"
Jack: JackPosixThread::StartImp : create non RT thread
[New Thread 0x7ffff73b26c0 (LWP 100915)]
Jack: JackPosixThread::ThreadHandler : start
Jack: Initializing PortAudio...                                                                                                                                                              
/usr/lib/libjack.so loaded successfully!                                                                                                                                                     
[New Thread 0x7fffef2006c0 (LWP 100916)]                                                                                                                                                     
[Thread 0x7fffef2006c0 (LWP 100916) exited]
[New Thread 0x7fffef2006c0 (LWP 100917)]
[New Thread 0x7fffee8006c0 (LWP 100918)]
[New Thread 0x7fffede006c0 (LWP 100919)]
Jack: JackPortAudioDriver::Open nframes = 128 in = 0 out = 0 capture name = JACK::system playback name = JACK::system samplerate = 48000
Jack: JackDriver::Open capture_driver_name = JACK::system
Jack: JackDriver::Open playback_driver_name = JACK::system
Jack: Check protocol client = 9 server = 9
Jack: JackEngine::ClientInternalOpen: name = system
Jack: JackEngine::AllocateRefNum ref = 0
Jack: JackLinuxFutex::Allocate name = jack_sem.1000_mod-desktop_system val = 0
Jack: JackEngine::NotifyAddClient: name = system
Jack: JackGraphManager::SetBufferSize size = 128
Jack: JackConnectionManager::DirectConnect first: ref1 = 0 ref2 = 0
Jack: JackGraphManager::ConnectRefNum cur_index = 0 ref1 = 0 ref2 = 0
Jack: JackDriver::SetupDriverSync driver sem in normal mode
Jack: JackPortAudioDriver::Open fInputDevice = 0, fOutputDevice 0
Jack: JackPortAudioDriver::Open setup max in channels = 2
Jack: JackPortAudioDriver::Open setup max out channels = 2
Jack: JackPortAudioDriver::OpenStream buffer_size = 128

Thread 1 "jackd" received signal SIGSEGV, Segmentation fault.
0x0000000000000000 in ?? ()
(gdb) bt
#0  0x0000000000000000 in ?? ()
#1  0x00007ffff731601e in jack_frame_time (client=0x5555556cecf0) at ../pipewire/pipewire-jack/src/pipewire-jack.c:6427
#2  0x00007fffef407fe7 in ?? () from /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/jack_portaudio.so
#3  0x00007fffef408d97 in ?? () from /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/jack_portaudio.so
#4  0x00007fffef40656f in ?? () from /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/jack_portaudio.so
#5  0x00007fffef4050ed in ?? () from /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/jack_portaudio.so
#6  0x00007fffef4056ca in ?? () from /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/jack_portaudio.so
#7  0x00007fffef405a7f in driver_initialize () from /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/jack/jack_portaudio.so
#8  0x00007ffff78c0aae in JackDriverInfo::Open(jack_driver_desc_t*, Jack::JackLockedEngine*, Jack::JackLinuxFutex*, _JSList const*) ()
   from /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/libjackserver.so.0
#9  0x00007ffff78be1c7 in Jack::JackServer::Open(jack_driver_desc_t*, _JSList*) () from /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/libjackserver.so.0
#10 0x00007ffff78c30d2 in jackctl_server_open () from /home/magillos/Downloads/mod-desktop-8d4e2463-linux-x86_64/mod-desktop/libjackserver.so.0
#11 0x0000555555402f53 in ?? ()
#12 0x00007ffff7d6dcd0 in ?? () from /usr/lib/libc.so.6
#13 0x00007ffff7d6dd8a in __libc_start_main () from /usr/lib/libc.so.6
#14 0x00005555554032ea in ?? ()
(gdb) 

```
(The app is amazing regardless of the issue!)

**Comment by falkTX** [comment]
potentially fixed with the latest 0.0.8 release, please check, thanks!

**Comment by Inqb8tr-jp** [comment]
On Manjaro the ver 0.0.8 works fine.
Thank you.

**Comment by thisven** [comment]
I experienced the same error with version 0.0.12 when starting it after Ardour has been started two times. However, now it seems to be no issue. The terminal output is:

```
MOD Desktop DEBUG: jacklib syms 0x76caf58267e0 (nil) | 65 | using regular jack
--------------------------------------------------------
libjack.so.0 loaded successfully!
--------------------------------------------------------
----------- loadSettings 654
----------- updateDeviceDetails 1028 | 5 6
----------- setStopped 782
----------- saveSettings 624
----------- start 872
----------- setStarting 758
----------- hostStartSuccess 1088
----------- hostStartError 1051
----------- setStopped 782
----------- getProcessErrorAsString 797
----------- showErrorMessage 811
```
